Repository clara-parabricks/GenomeWorks, pull requests merged in 2019-10, with the labels that each got.

#164 add dropped group after batch.reset
  pyclaragenomics/samples/sample_cudapoa
Labels: bug

#173 [cudamapper] Multithreaded implementation of IndexGPU::build_index
  cudamapper/src/index_gpu.cu
  cudamapper/src/index_gpu.cuh
  cudamapper/tests/Test_CudamapperIndexGPU.cu
Labels: cudamapper, enhancement

#174 [CGA] Listed additional packages which should be installed on fresh U…
  README.md
Labels: documentation, sdk
